version: "3.1"
services:
    api:
        build:
            context: ./api
            dockerfile: dev.Dockerfile
        container_name: better_dime_api
        volumes:
            - ./api:/api
        working_dir: /api
        command: "rails server -p 8000 -b 0.0.0.0"
        depends_on:
            - mysql
        ports:
            - "18000:8000"
        environment:
            - DATABASE_HOST=mysql
            - DATABASE_USERNAME=root
            - DATABASE_PASSWORD=
    frontend:
        image: node:10
        container_name: better_dime_frontend
        volumes:
            - ./frontend:/var/frontend
        working_dir: /var/frontend
        ports:
            - "13000:3000"
        command: bash -c "yarn install && yarn run start"
    mysql:
        image: mariadb:10.3.14
        container_name: better_dime_db
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "13306:3306"
        volumes:
            - ./database:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: better_dime_phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 18080:80

