# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.5"

gem "axlsx_styler"
gem "bootsnap", ">= 1.1.0", require: false
gem "caxlsx_rails"
gem "creek"
gem "deep_cloneable", "~> 3.0.0"
gem "devise-jwt", "~> 0.6"
gem "discard"
gem "dotenv-rails"
gem "draper"
gem "dry-configurable", "~> 0.9.0" # Regression issue of the latest devise-jwt and it's dependencies, could be removed
gem "health-monitor-rails"
gem "jbuilder"
gem "kaminari"
gem "mysql2", ">= 0.4.4", "< 0.6.0"
gem "paper_trail"
gem "prawn"
gem "prawn-table"
gem "puma", "~> 4.3"
gem "rack-cors", require: "rack/cors"
gem "rails", "~> 6.0.1"
gem "ransack"
gem "redcarpet"
gem "validates_timeliness"

group :production do
  gem "lograge"
  gem "sentry-raven"
end

group :development, :test do
  gem "brakeman", require: false
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "debase"
  gem "factory_bot_rails"
  gem "faker"
  gem "pry-byebug"
  gem "pry-rails"
  gem "rails-controller-testing"
  gem "rspec-rails", "4.0.0.beta3"
  gem "rubocop", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rspec", require: false
  gem "ruby-debug-ide"
end

group :development do
  gem "better_errors"
  gem "binding_of_caller"
  gem "letter_opener"
  gem "listen", ">= 3.0.5", "< 3.2"
  # gem 'spring'
  # gem 'spring-watcher-listen', '~> 2.0.0'
  gem "guard-brakeman"
  gem "guard-rspec"
  gem "guard-rubocop"
end

group :test do
  gem "shoulda-matchers"
  gem "simplecov", require: false
  gem "test-prof", require: false
end

gem "tty-table"
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
