# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~> 3.4.0"

gem "bootsnap", ">= 1.1.0", require: false
gem "caxlsx_rails"
gem "creek"
gem "deep_cloneable", "~> 3.2.0"
gem "devise-jwt", "~> 0.12"
gem "discard", "~> 1.3"
gem "dotenv-rails"
gem "draper", "~> 4.0"
gem "health-monitor-rails"
gem "jbuilder"
gem "kaminari"
gem "mysql2", ">= 0.4.4"
gem "paper_trail", "~> 16.0"
gem "prawn"
gem "prawn-table"
gem "puma", "~> 6.4"
gem "qr-bills"
gem "rack-cors", "~> 2.0", require: "rack/cors"
gem "rails", "~> 8.0.0"
gem "ransack", "~> 4.0"
gem "redcarpet"
gem "validates_timeliness", "~> 8.0"

group :production do
  gem "lograge"
  gem "sentry-rails", "~> 5.17"
  gem "sentry-ruby", "~> 5.17"
end

group :development, :test do
  gem "brakeman", require: false
  gem "debug"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.0"
  gem "pry-rails"
  gem "rails-controller-testing"
  gem "rspec-rails", "~> 7.0"
  gem "rubocop", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", "~> 2.15", require: false
  gem "rubocop-rspec", require: false
end

group :development do
  gem "better_errors"
  gem "binding_of_caller"
  gem "letter_opener"
  gem "listen"
  gem "guard-brakeman"
  gem "guard-rspec"
  gem "guard-rubocop"
end

group :test do
  gem "rspec-openapi"
  gem "shoulda-matchers", "~> 6.0"
  gem "simplecov", require: false
  gem "test-prof", require: false
end

gem "tty-table"
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
