name: "Better-iZivi CD (Docker)"

on:
  push:
    branches:
      - develop
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: ${{ github.repository }}-api
  FRONTEND_IMAGE_NAME: ${{ github.repository }}-frontend

jobs:
  build-push-api:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for API Docker
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref_name == 'master' }}

      - name: Build and push API Docker image
        id: push-api
        uses: docker/build-push-action@v5
        with:
          context: apir
          file: apir/prod.Dockerfile
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}

  build-push-frontend:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for FRONTEND Docker
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref_name == 'master' }}

      - name: Build and push Frontend Docker image
        id: push-frontend
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/prod.Dockerfile
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          build-args: |
            ENVIRONMENT=${{ secrets.ENVIRONMENT }}
            SENTRY_DSN_PUBLIC=${{ secrets.SENTRY_DSN_PUBLIC }}
            APIR_URL=${{ secrets.APIR_URL }}
            FEEDBACKS_URL=${{ secrets.FEEDBACKS_URL }}
