name: "Better-Dime CD"

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  develop:
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup the SSH known hosts file"
        run: |
          mkdir -p -m 0700 /home/runner/.ssh
          echo $HOST_KEY >> /home/runner/.ssh/known_hosts
          chmod 600 /home/runner/.ssh/known_hosts
        env:
          HOST_KEY: ${{ secrets.SSH_HOST_KEY }}

      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote
        run: git remote add metanet swo@stiftungswo.ch:~/git/better-dime/develop.git

      - name: Push
        run: git push -f metanet $BRANCH_NAME:master
        env:
          BRANCH_NAME: ${{ github.ref_name }}

  master:
    runs-on: ubuntu-latest
    environment: master

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup the SSH known hosts file"
        run: |
          mkdir -p -m 0700 /home/runner/.ssh
          echo $HOST_KEY >> /home/runner/.ssh/known_hosts
          chmod 600 /home/runner/.ssh/known_hosts
        env:
          HOST_KEY: ${{ secrets.SSH_HOST_KEY }}

      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote
        run: git remote add metanet swo@stiftungswo.ch:~/git/better-dime/master.git

      - name: Push
        run: git push -f metanet $BRANCH_NAME:master
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        
